name: CI
on:
  push:
    branches:
      - lhci
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.3
      - name: yarn install, build
        run: |
          yarn
          yarn build
      - name: run Lighthouse CI
        run: |
          yarn lhci
